#!/usr/bin/env bash

add_ld_library_path() {
  if test -z "$LD_LIBRARY_PATH"
  then
    LD_LIBRARY_PATH="$1"
  else
    LD_LIBRARY_PATH="$1:$LD_LIBRARY_PATH"
  fi
}

"$basedir/abicheck" >/dev/null 2>&1
if [ $? -ne 0 ]; then
  add_ld_library_path "${APPDIR}/opt/tor-proxy/libstdc++/"
fi
add_ld_library_path "${APPDIR}/opt/tor-proxy/"
export LD_LIBRARY_PATH


${APPDIR}/opt/tor-proxy/tor &

${APPDIR}/opt/tor-browser/chrome --proxy-server="socks://127.0.0.1:9050" --profile-directory=Tor-Browser $@ https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion
